
// Common postal code regex patterns
// Source: Aggregated from multiple open-source repositories

export const POSTAL_CODE_REGEX: Record<string, RegExp> = {
    "India": /^[1-9][0-9]{5}$/,
    "United States": /^\d{5}(-\d{4})?$/,
    "United Kingdom": /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i,
    "Canada": /^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z] ?\d[ABCEGHJ-NPRSTV-Z]\d$/i,
    "Australia": /^\d{4}$/,
    "Germany": /^\d{5}$/,
    "France": /^\d{5}$/,
    "Italy": /^\d{5}$/,
    "Spain": /^\d{5}$/,
    "Japan": /^\d{3}-\d{4}$/,
    "China": /^\d{6}$/,
    "Russia": /^\d{6}$/,
    "Brazil": /^\d{5}-\d{3}$/,
    "Mexico": /^\d{5}$/,
    "Argentina": /^[A-Z]\d{4}[A-Z]{3}$/,
    "Netherlands": /^\d{4} ?[A-Z]{2}$/,
    "Switzerland": /^\d{4}$/,
    "Sweden": /^\d{3} ?\d{2}$/,
    "Norway": /^\d{4}$/,
    "Denmark": /^\d{4}$/,
    "Finland": /^\d{5}$/,
    "Poland": /^\d{2}-\d{3}$/,
    "Belgium": /^\d{4}$/,
    "Austria": /^\d{4}$/,
    "Portugal": /^\d{4}-\d{3}$/,
    "South Africa": /^\d{4}$/,
    "New Zealand": /^\d{4}$/,
    "Singapore": /^\d{6}$/,
    "Malaysia": /^\d{5}$/,
    "South Korea": /^\d{5}$/,
    "Bangladesh": /^\d{4}$/,
    "Pakistan": /^\d{5}$/,
    "Sri Lanka": /^\d{5}$/,
    "Nepal": /^\d{5}$/,
    "Bhutan": /^\d{4}$/,
    "Afghanistan": /^\d{4}$/,
    "Albania": /^\d{4}$/,
    "Algeria": /^\d{5}$/,
    "Andorra": /^AD\d{3}$/,
    "Angola": /^\d{6}$/, // Not strictly enforced but commonly 6 digits
    "Armenia": /^\d{4}$/,
    "Azerbaijan": /^AZ\d{4}$/,
    "Bahrain": /^\d{3,4}$/,
    "Belarus": /^\d{6}$/,
    "Bulgaria": /^\d{4}$/,
    "Cambodia": /^\d{5}$/,
    "Chile": /^\d{7}$/,
    "Colombia": /^\d{6}$/,
    "Costa Rica": /^\d{4,5}$/,
    "Croatia": /^\d{5}$/,
    "Cuba": /^\d{5}$/,
    "Cyprus": /^\d{4}$/,
    "Czech Republic": /^\d{3} ?\d{2}$/,
    "Dominican Republic": /^\d{5}$/,
    "Ecuador": /^\d{6}$/,
    "Egypt": /^\d{5}$/,
    "Estonia": /^\d{5}$/,
    "Ethiopia": /^\d{4}$/,
    "Greece": /^\d{3} ?\d{2}$/,
    "Guatemala": /^\d{5}$/,
    "Haiti": /^\d{4}$/,
    "Honduras": /^\d{5}$/,
    "Hong Kong": /./, // No postal code system strictly
    "Hungary": /^\d{4}$/,
    "Iceland": /^\d{3}$/,
    "Indonesia": /^\d{5}$/,
    "Iran": /^\d{10}$/,
    "Iraq": /^\d{5}$/,
    "Ireland": /./, // Eircode is complex, allowing generic for now
    "Israel": /^\d{5}(\d{2})?$/,
    "Jordan": /^\d{5}$/,
    "Kazakhstan": /^\d{6}$/,
    "Kenya": /^\d{5}$/,
    "Kuwait": /^\d{5}$/,
    "Kyrgyzstan": /^\d{6}$/,
    "Latvia": /^LV-\d{4}$/,
    "Lebanon": /^\d{4}(\d{4})?$/,
    "Lithuania": /^LT-\d{5}$/,
    "Luxembourg": /^\d{4}$/,
    "Macedonia": /^\d{4}$/,
    "Madagascar": /^\d{3}$/,
    "Malta": /^[A-Z]{3} ?\d{2,4}$/,
    "Moldova": /^\d{4}$/,
    "Monaco": /^980\d{2}$/,
    "Mongolia": /^\d{5}$/,
    "Montenegro": /^\d{5}$/,
    "Morocco": /^\d{5}$/,
    "Mozambique": /^\d{4}$/,
    "Myanmar": /^\d{5}$/,
    "Namibia": /^\d{4}$/,
    "Nicaragua": /^\d{5}$/,
    "Nigeria": /^\d{6}$/,
    "Oman": /^\d{3}$/,
    "Panama": /^\d{4}$/,
    "Paraguay": /^\d{4}$/,
    "Peru": /^\d{5}$/,
    "Philippines": /^\d{4}$/,
    "Romania": /^\d{6}$/,
    "Saudi Arabia": /^\d{5}$/,
    "Senegal": /^\d{5}$/,
    "Serbia": /^\d{5}$/,
    "Slovakia": /^\d{3} ?\d{2}$/,
    "Slovenia": /^\d{4}$/,
    "Sudan": /^\d{5}$/,
    "Taiwan": /^\d{3}(\d{2})?$/,
    "Tajikistan": /^\d{6}$/,
    "Thailand": /^\d{5}$/,
    "Tunisia": /^\d{4}$/,
    "Turkey": /^\d{5}$/,
    "Turkmenistan": /^\d{6}$/,
    "Ukraine": /^\d{5}$/,
    "Uruguay": /^\d{5}$/,
    "Uzbekistan": /^\d{6}$/,
    "Venezuela": /^\d{4}$/,
    "Vietnam": /^\d{6}$/,
    "Zambia": /^\d{5}$/,
};

export const DEFAULT_POSTAL_CODE_REGEX = /^[a-zA-Z0-9\s-]{3,10}$/; // Fallback Generic
